#INCLUDE "PROTHEUS.CH"

/*-------------------------------------------------------------------------------------
{Protheus.doc} AFTERLOGIN

@Author  	   Felipe Aguiar - Focus Consultoria
@since		   05/2019
@version	   P12

@description Funcao executada apos login no sistema
---------------------------------------------------------------------------------------
|Author                  | Date       | Description                                    |
|                        |            |                                                |
--------------------------------------------------------------------------------------*/
User Function AFTERLOGIN()

Public c_Msblql := "" // Variavel utilizada no PE MATA010_PE 

Return Nil